### ISSUE TITLE
Problem with buttons

### ISSUE THREAD

**Issue by LennAl** [node-red/node-red.github.io#115]
I programmed a small survey where I used buttons to get on the next page. When I opend my survey in the browser on my tablet I had to push the button twice to get to the next page. Then I wrote a Tooltip for my button and than it worked and I only had to push the button once. But without the Tooltip it does not realy work like I wish.

**Comment by knolleary** [comment]
Hi, what relation does your issue have to Node-RED or its website?

**Comment by LennAl** [comment]
I programmed my survey with Node-Red

**Comment by knolleary** [comment]
This repository is for issues relating to the node-red website, it is not a general support channel.

Please use the [community forum](https://discourse.nodered.org). When you post there you will need to provide *a lot* more detail, such as how you have created the survey, whether it is using node-red dashboard or some other custom thing.

**Comment by LennAl** [comment]
The usual function does already work (for the button that should be clicked by the user once), but only in corelation with the fact, that a tooltip is defined in the object. So, if I delete an existing tooltip in my object, then the user has to click twice. So my question is why should be direct reference between the usage of the "click"-button and the tooltip? Because otherwise in my opinion it`s weird. Thanks for your help in advance and best regards.

**Comment by knolleary** [comment]
@LennAl and that is a question no one can answer unless you explain in more detail what you are doing. How have you created the button, how have you added the tooltip, is this all custom javascript/html you've written or are you using one of the various dashboarding sets of nodes that are available. Without those basic details, we won't know where to start answering the question. So when you do post to the forum, make sure you include enough detail, otherwise you'll be asked all the same questions. Thanks

**Comment by LennAl** [comment]
@knolleary  I tried to summerize those steps that I made with Node-Red (please note the attachement). I did not wrote or adapt in any language. I just tried to design a process workflow. I hope you can understand my question now a bit better. Thankyou very much for your support.
[Process description.pdf](https://github.com/node-red/node-red.github.io/files/3338579/Process.description.pdf)

**Comment by knolleary** [comment]
This issue is closed. We do not do support here. Please use the forum I linked to in my original reply. All of my responses since have been advice for when you post to the forum.
