### ISSUE TITLE
Worldmap tracks

### ISSUE THREAD

**Issue by ChristopherO1** [node-red/node-red.github.io#120]
As requested by dceejay

https://discourse.nodered.org/t/worldmap-gps-tracking/13895

Setting up worldmap, and tracking GPS devices.
Every so often tracks are not not drawn between some of the points - see forum link above.

Also when the traces reach the max as defined in the tracks node, the trace is cleared and restarted, rather than just losing the oldest point.

As requested data for the devices being tracked

[
[DraginoData.txt](https://github.com/node-red/node-red.github.io/files/3470967/DraginoData.txt)
](url)

[AbeewayData.txt](https://github.com/node-red/node-red.github.io/files/3470968/AbeewayData.txt)

**Comment by knolleary** [comment]
Hi, this is the issue tracker for the Node-RED website and documentation.

It is not a place to raise issues against nodes, particularly nodes that are not maintained by the Node-RED project itself.

The worldmap node's repository is here: https://github.com/dceejay/RedMap
