### ISSUE TITLE
Documentation typo - EditableList Widget - resizeItem

### ISSUE THREAD

**Issue by scottpageindysoft** [node-red/node-red.github.io#132]
[resizeItem](https://nodered.org/docs/api/ui/editableList/#options-resizeItem)

console is misspelled.

`$("ol.list").editableList({
    resizeItem: function(row,index) {
        var originalData = $(row).data('data');
        consol.log("Resize the row for item:", originalData)
    }
});`

Should read: `console.log("Resize the row for item:", originalData)`

**Comment by knolleary** [comment]
Moved to the repo for the docs. 

If you wanted to PR the fix, the file is here: https://github.com/node-red/node-red.github.io/blob/master/docs/api/ui/editableList/index.md

**Comment by scottpageindysoft** [comment]
@knolleary thanks!  I'm getting used to the repository structure.

I'll PR it.

**Comment by knolleary** [comment]
Fixed by #133
