### ISSUE TITLE
no longer available to use earthquake csv file

### ISSUE THREAD

**Issue by taijihagino** [node-red/node-red.github.io#151]
No data is on the earthquake csv for Tutorial -> Getting your second flow -> 2. Add an HTTP Request node
https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.csv

I recommend another csv instead of it.
e.g. To use http://weather.livedoor.com/weather_hacks/webservice for this tutorial. (in Japanese)

**Comment by dceejay** [comment]
You can try https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_month.csv instead. 
Unusually there have been very few significant earthquakes this past week

**Comment by taijihagino** [comment]
I can see the csv, thanks!

**Comment by dceejay** [comment]
I updated the doc to point to the month one so there should be something there now. (not that we want significant earthquakes... but it has been unusually quiet)

**Comment by taijihagino** [comment]
absolutely I hope we have no earthquake.
thanks for updating it:)
