### ISSUE TITLE
Creating your first node example uses outdated label syntax

### ISSUE THREAD

**Issue by rianadon** [node-red/node-red.github.io#165]
The example code for `lower-case.html` in the [Creating your first node](https://nodered.org/docs/creating-nodes/first-node) guide uses the following syntax for creating the label that appears next to where you'd give the node its name:
```html
 <label for="node-input-name"><i class="icon-tag"></i> Name</label>
```

In the latest version of node-red, the icon doesn't appear. However, the [Node properties](https://nodered.org/docs/creating-nodes/properties) guide uses this syntax which works:
```html
<label for="node-input-name"><i class="fa fa-tag"></i> Name</label>
```

It appears the node properties page was updated to reflect the icon switch but the lower case example hasn't yet been updated.

**Comment by dceejay** [comment]
good spot - thanks
