### ISSUE TITLE
Document `-input`, `-output` convention for category

### ISSUE THREAD

**Issue by garnold** [node-red/node-red.github.io#17]
Per the [HTML File](http://nodered.org/docs/creating-nodes/node-html.html) documentation, you can use the `<space>in`, `<space>out` convention in the node type to denote input and output nodes, respectively.  The documentation should also mention that you can use the `-input`, `-output` convention in the node category to group input and output nodes together.

**Comment by dceejay** [comment]
Closed due to PR merge
