### ISSUE TITLE
Tiny grammatical issue in tutorial

### ISSUE THREAD

**Issue by Dustpancake** [node-red/node-red.github.io#173]
In the ["Creating your first flow"](https://github.com/node-red/node-red.github.io/blob/master/docs/tutorials/first-flow.md) tutorial, on line 12-13, section "Overview":
```
This tutorial introduces the Node-RED editor and creates a flow the demonstrates
the Inject, Debug and Function nodes.
```
I believe this should read: `[...] a flow that demonstrates [...]` (using *that* over *which*, since it is a restrictive clause)

**Comment by knolleary** [comment]
Thanks - feel free to PR and other typos like that.
