### ISSUE TITLE
Linking containers in Docker uses a deprecated feature

### ISSUE THREAD

**Issue by binnes** [node-red/node-red.github.io#186]
The [Docker section](https://nodered.org/docs/getting-started/docker#linking-containers) about linking containers needs to be updated to use the --network options rather than --link, as the --link option is [now deprecated](https://docs.docker.com/network/links/)

**Comment by knolleary** [comment]
The 'source' of that page (not directly... but the info should be consistent) is the readme for the node-red-docker repository - so any updates to one should be reflected in the other - https://github.com/node-red/node-red-docker

**Comment by lazyzero** [comment]
Not sure if you prefer to reopen the issue or if I do a new one?

The example to link mosquitto by a bridge network dosn't work with mosquitto:latest (2.0.7) but with the last 1.6.13 seams that the config file of Mosquitto 2 is different and not listeneing to the network by default.

Best Christian

**Comment by dceejay** [comment]
New issue please - and ideally a fix as well :-)
