### ISSUE TITLE
missing word in documentation - single line fix

### ISSUE THREAD

**Issue by joe-pearson-me** [node-red/node-red.github.io#189]
On the [following page](https://nodered.org/docs/getting-started/docker), you are likely missing a word in this sentence:

`Environment variables can be passed into the container configure the runtime of Node-RED.`

You likely _meant_ to say:

"Environment variables can be passed into the container **to** configure the runtime of Node-RED."

**Comment by dceejay** [comment]
thanks will fix in next release.
