### ISSUE TITLE
Issue on upgrading the node info

### ISSUE THREAD

**Issue by FStefanni** [node-red/node-red.github.io#194]
Hi,

I have noticed that the version of a custom node I maintain is not up-to-date.

Here you can see that it states 1.1.3 (a very old version!):
https://flows.nodered.org/node/@open-kappa/node-red-contrib-mydb

but it is actually 1.4.0 as reported by npm:
https://www.npmjs.com/package/@open-kappa/node-red-contrib-mydb

Since it seems everything fine within the package.json, I am expecting that this is an issue by the site auto-discovery mechanism,
and maybe this is affecting also nodes by others.

Regards

**Comment by knolleary** [comment]
There is no longer an auto-discovery mechanism. You have to request an update by the 'request refresh' link no your node's page.

This change was announced earlier in the year when we had to disable the auto-discovery mechanism due to ongoing unreliability of npm search.

**Comment by FStefanni** [comment]
OK thanks, I didn't noticed. Request done.

Regards
