### ISSUE TITLE
Confusing node-red start stop description for RasPi

### ISSUE THREAD

**Issue by pz1** [node-red/node-red.github.io#21]
The instruction for start/stop Raspberry Pi Jessie at the beginning of the document and further to the bottom are different. The latter caters for limited memory in Pi, the first does not.

**Comment by knolleary** [comment]
Hi,

when using the preinstalled Node-RED on Jessie, all of the memory management arguments are handled for you - so you don't need to set them.

When running from a manually installed version, you have to set them.

Will see what we can do to clarify without overburdening the user with too much information that they don't need (in the preinstalled case).

**Comment by pz1** [comment]
Thanks. I guessed that was the case, but as a noob I felt uneasy about it.

**Comment by pz1** [comment]
Changed text is OK with me. So I close this issue
