### ISSUE TITLE
typedInput change event example don't match the method params

### ISSUE THREAD

**Issue by Zehir** [node-red/node-red.github.io#217]
One image is better than 1000 words ;)
We missing the `event` var in the function fo the exemple.
![image](https://user-images.githubusercontent.com/845225/115456466-7a0a9100-a223-11eb-91f9-8975fd156aab.png)

**Comment by knolleary** [comment]
A Pull Request that fixes it is worth even more ;)

**Comment by Zehir** [comment]
> A Pull Request that fixes it is worth even more ;)

I was think about that but then I see this in the README 'For simple typos and single line fixes please just raise an issue pointing out our mistakes.'

**Comment by knolleary** [comment]
I guess we should change that to not put off contributions.

No problem, I'm fixing up the docs around disable/enable as per the other issue we discussed now that 1.3.3 has been released.
