### ISSUE TITLE
Node-RED documentation improvment proposal for the "Loading extra resources in the editor" section

### ISSUE THREAD

**Issue by antoine-em** [node-red/node-red.github.io#227]
I wanted to share my experience about loading extra resources in a scoped module.
As it is not described in the documentation I spent some time to figure it out and so I would like to share my experience.

Location -> https://nodered.org/docs/creating-nodes/resources
> docs • creating nodes • resources > Loading extra resources in the editor

#### Solution for a scoped module

- In the package.json copy the full name with the scope
- add the resource file as described in the current documentation under the `resources` folder at the root of the module
- in the browser open with the following url to test (example with localhost) -> http://localhost:1880/resources/@scope/node-red-contrib-your-package/somefile

**Comment by knolleary** [comment]
Thanks for the feedback @antoine-em 

I had assumed it would be clear that where we have `/resources/<name-of-module>/<path-to-resource>.`, that `name-of-module` would be the full name including scope.

We can certainly add a note to make that explicit.
