### ISSUE TITLE
Document default environment variables

### ISSUE THREAD

**Issue by dgilleland** [node-red/node-red.github.io#272]
As noted in the forum post ["List of default environment variables"](https://discourse.nodered.org/t/list-of-default-environment-variables/61936), it would be helpful to have these environment variables listed in the documentation.

I would be happy to do a pull-request solution for this.

@knolleary - Is there any particular page you would like to see this documented? I'm thinking the `docs/user-guide/environment-variables.md` file.

**Comment by knolleary** [comment]
That is probably the best place at the moment.

**Comment by dgilleland** [comment]
Ok. I'll aim to have a pull request ready by Monday.
