### ISSUE TITLE
0.17: document optional 'removed' parameter on node close handler

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red.github.io#44]
```
this.on('close', function(removed, done) {
    if (removed) {
        // this node isn't going to be recreated
    }
    doSomethingWithACallback(function() {
        done();
    });
});
```

**Comment by hardillb** [comment]
Should removed, done be the other way round?

Then old code will still work (or have I miss understood?)

```
this.on('close', function(done) {

}
```


```
this.on('close', function(done, removed) {

}
```

**Comment by knolleary** [comment]
The node.js convention is the `done` arg goes last.

Existing code will continue to work as we check how many args the provided function has and construct the appropriate args array to pass it.

**Comment by hardillb** [comment]
cool
