### ISSUE TITLE
Security function has verify callback in the wrong place.

### ISSUE THREAD

**Issue by sparkpunkd** [node-red/node-red.github.io#55]
On page `docs/security.md`, the example for OAuth using Twitter in section _OAuth/OpenID based authentication_ has a `verify` callback function. When trying out the example, this function is never called.

Reading the code [here](https://github.com/node-red/node-red/blob/78076122baf717152ba1a7fa0a19c0beaac40173/red/api/auth/index.js#L169) suggests that the verify callback function needs to be a field inside the `options` object. Testing this approach, the function is then called. See the alternative example below:

```javascript
adminAuth: {
        type:"strategy",
        strategy: {
            name: "twitter",
            label: 'Sign in with Twitter',
            icon: "fa-twitter",
            strategy: require("passport-twitter").Strategy,
            options: {
                consumerKey: TWITTER_APP_CONSUMER_KEY,
                consumerSecret: TWITTER_APP_CONSUMER_SECRET,
                callbackURL: "http://example.com/auth/strategy/callback",
                verify: function(token, tokenSecret, profile, done) {
                  console.log('***', profile);
                  done(null, profile);
                }
            },
        },
        users: [
           { username: "StrmPunkd", permissions: ["*"] }
        ]
    },
```

Can the documentation be updated appropriately (without the console.log call!)?

**Comment by knolleary** [comment]
oops - well spotted. Looks like our example twitter and github auth plugins also need updating (although through good fortune, the fact they don't provide a verify function doesn't actually stop them working).

**Comment by knolleary** [comment]
The doc update for this was made quite some time ago. Finally got around to publishing the updated versions of the Twitter/Github plugins. All good now.
