### ISSUE TITLE
User docs assume some basic Javascript experience

### ISSUE THREAD

**Issue by mblackstock** [node-red/node-red.github.io#69]
Should add a note indicating this up front, and make things clearer such as modifying settings.js file by adding new key/value pair to settings to enable projects.

**Comment by dceejay** [comment]
go for it... emphasising the Javascript not Java...

**Comment by mblackstock** [comment]
put Javascript in **BOLD** ...

**Comment by dceejay** [comment]
Merged PR to resolv
