### ISSUE TITLE
Node 10 LTS support

### ISSUE THREAD

**Issue by tkurki** [node-red/node-red.github.io#88]
### What are the steps to reproduce?

Read the documentation and see _Node.js LTS 8.x_ as the recommended and latest version.

### What happens?

Disappointment at Node.js 10, the newly current LTS, not officially supported.

### What do you expect to happen?

Read announcement about  supporting or even recommendation for Node.js 10 or indication if Node-RED is known to work on it.

### Please tell us about your environment:

- [X] Node-RED version:0.19.5
- [X] node.js version:v8.12.0

**Comment by knolleary** [comment]
I have transferred this issue over to the website repository - as that's where we need to update the docs. I'll reopen until we make that update.

**Comment by knolleary** [comment]
I've just posted [this topic](https://discourse.nodered.org/t/support-for-node-js-10-lts/4489) to the forum on this subject.

**Comment by dceejay** [comment]
closed to due docs upgrade - https://nodered.org/docs/faq/node-versions
