### ISSUE TITLE
Termux API link is broken

### ISSUE THREAD

**Issue by s1r-J** [node-red/node-red.github.io#95]
In docs/platforms/android page, click "How to use Termux API" link to encounter "Page not found".

Node-RED: https://nodered.org/docs/platforms/android
![termux](https://user-images.githubusercontent.com/35455687/52561057-9b9ab180-2e3d-11e9-9076-df25fd6aa109.PNG)

Termux: https://termux.com/add-on-api.html
![notfound](https://user-images.githubusercontent.com/35455687/52561059-9dfd0b80-2e3d-11e9-9398-c4e4efb99a8f.PNG)

Maybe, the url is changed to https://wiki.termux.com/wiki/Termux:API

**Comment by dceejay** [comment]
Thanks for spotting that (and the new correct link)
