### ISSUE TITLE
Broken design at Runtime API

### ISSUE THREAD

**Issue by ryoichi-obara** [node-red/node-red.github.io#97]
![docs-api-runtime-api](https://user-images.githubusercontent.com/2470145/53064556-9ad3e080-350b-11e9-8af1-174e25189c99.png)

https://nodered.org/docs/api/runtime/api

**Comment by knolleary** [comment]
Hi,

This isn't broken, we've just never published the API


The work being done for 0.20 includes docs for the API.

**Comment by ryoichi-obara** [comment]
Okay, I understand. Thank you.
